spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 9446440812@Ad
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG
    com.healthcare: DEBUG
